const IMAGES = {
	LOAD: 'IMAES_LOAD',
	LOAD_SUCCESS: 'IMAES_LOAD_SUCCESS',
	LOAD_FAIL: 'IMAES_LOAD_FAIL',
};

const STATS = {
	LOAD: 'IMAES_LOAD',
	LOAD_SUCCESS: 'IMAES_LOAD_SUCCESS',
	LOAD_FAIL: 'IMAES_LOAD_FAIL',
};

export { IMAGES, STATS };
